XLS file downlaod formatting fix
tiramizoo/reactable pull request #23
Opened 2023-01-09 08:59 UTC by AOneP

https://3.basecamp.com/3198361/buckets/3856681/messages/5577317219

2023-01-11 19:08 UTC, MBO requested changes
Overall looks good, just one last change to `date` formatting if it's null.

2023-01-11 19:08 UTC, MBO commented on src/components/DownloadXlsx/DownloadXlsx.jsx
> +        let date = new Date(value)
You can add `if (value)` there too, just to be safe

2023-01-11 19:11 UTC, AOneP commented on src/components/DownloadXlsx/DownloadXlsx.jsx
> +        let date = new Date(value)
I can't find w view with no "date". 
I'll check and confirm before 8AM

2023-01-12 09:23 UTC, MBO approved these changes

2023-01-12 09:40 UTC, morgoth commented on src/components/DownloadXlsx/DownloadXlsx.jsx
> +          return new Date(date.getTime() - date.getTimezoneOffset() * 60 * 1000)
I can see that we're using luxon in the project. Wouldn't be somehow easier to use it for timezones? https://moment.github.io/luxon/#/zones

2023-01-12 11:36 UTC, merged

2023-01-12 11:36 UTC, morgoth commented
@AOneP Can you prepare PR for dataclips?

2023-01-12 15:57 UTC, MBO commented on src/components/DownloadXlsx/DownloadXlsx.jsx
> +          return new Date(date.getTime() - date.getTimezoneOffset() * 60 * 1000)
@morgoth The thing is we need to create Date object anyway, and we have to create it so that UTC time points to correct local time, i.e. 15:35 in +2:00 timezone should be saved as 15:35 GMT, because Excel doesn't store timezones, it only shows local times without timezone context.

There is one more issue here, because this doesn't take into account organization's timezone offset.